### PR TITLE
bioconda implementation

### PR DESCRIPTION
**Pull request by SilasK**
This allows using DAS tool in environments, e.g. bioconda

Could you make a new release?

### CODE REVIEW

**Comment by SilasK** [comment]
#13

**Comment by SilasK** [comment]
This PR is necessary for a bioconda impementations. 
@cmks  could you follow [this PR](https://github.com/bioconda/bioconda-recipes/pull/10528)?

**Comment by SilasK** [comment]
@cmks, you worked on a solution to #26 , could you commit this changes so it's solved when we build a bioconda package.

**Comment by SilasK** [comment]
@cmks Could you make a new release, e.g. v1.1.1

**Comment by cmks** [comment]
Yes, I'm also implementing bug fixes for #26 in 1.1.1. Will release in the next days.

**Comment by SilasK** [comment]
Great

**Comment by SilasK** [comment]
@cmks  Redy to release the new code?

**Pull request merged**
